# Generated by Django 5.2.17 on 2026-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='trips_fuels_latitud_23b574_idx')],
            },
        ),
    ]
